---
- name: ensure personal login packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  register: install_packages
  with_items:
    - gnucash
